version: 1.0.{build}
build:
  verbosity: minimal
notifications:
  - provider: Email
    to:
      - PerezHz@users.noreply.github.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false